### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by LucianAndries** [dalion619/disney-plus-win10-desktop-uwp#3]
Hello.

I tried installing it like you shown, but it's not working............. With and without admin rights.
Please advise!

This is the error message with no admin rights:

Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFF, To install this application you need either a Windows dev
eloper license or a sideloading-enabled system.
Deployment of package Disney.37853FC22B2CE_1.10.13.70_x64__6rarf9sa4v8jt with package origin Unsigned failed because no
 valid license or sideloading policy could be applied. A developer license (http://go.microsoft.com/fwlink/?LinkId=2330
74) or enterprise sideloading configuration (http://go.microsoft.com/fwlink/?LinkId=231020) may be required.
NOTE: For additional information, look for [ActivityId] 54c61ac5-4ce4-000a-daaf-c654e44cd701 in the Event Log or use th
e command line Get-AppPackageLog -ActivityID 54c61ac5-4ce4-000a-daaf-c654e44cd701
At line:1 char:1
+ Add-AppxPackage -Register .\Disney.37853FC22B2CE_1.10.13.70_x64__6rar ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\Temp\D...ppXManifest.xml:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by LucianAndries** [comment]
This is the error with admin rights:

Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFF, To install this application you need either a Windows dev
eloper license or a sideloading-enabled system.
Deployment of package Disney.37853FC22B2CE_1.10.13.70_x64__6rarf9sa4v8jt with package origin Unsigned failed because no
 valid license or sideloading policy could be applied. A developer license (http://go.microsoft.com/fwlink/?LinkId=2330
74) or enterprise sideloading configuration (http://go.microsoft.com/fwlink/?LinkId=231020) may be required.
NOTE: For additional information, look for [ActivityId] 54c61ac5-4ce4-000c-d08d-c654e44cd701 in the Event Log or use th
e command line Get-AppPackageLog -ActivityID 54c61ac5-4ce4-000c-d08d-c654e44cd701
At line:1 char:1
+ Add-AppxPackage -Register .\Disney.37853FC22B2CE_1.10.13.70_x64__6rar ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\WINDOWS\syst...ppXManifest.xml:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by LucianAndries** [comment]
Oh and installing it from this, the app itself installs:
Disney.37853FC22B2CE_1.4.7.0_x64__6rarf9sa4v8jt.appx

But after that it asks for Update and redirects me to the MS Store anyway.....
Can we install .emsix files? Or can we make it stop asking for updates?

Thank you.

**Comment by kentnek** [comment]
@LucianAndries I found a temporary workaround by intercepting API requests from the app to Disney+ server using Telerik, so that whenever it asks for the minimum required version, Telerik will return the old version number instead. However, I'm still getting 1280x720 as the maximum resolution (at least from the API response). 

I notice that the app was requesting video info from `/scenarios/restricted-drm-ctr-sw`, so it's highly likely that this old version of the Disney+ UWP app does not pass DRM validations to get anything higher than 720p :(

```json
// https://disney.playback.edge.bamgrid.com/media/60a600e8-1306-4118-b96b-b0b1f783871a/scenarios/restricted-drm-ctr-sw
{
  "variants": [
      {
        "bandwidth": 933674,
        "resolution": "640x360",
        "videoBytes": 117700933,
        "maxAudioRenditionBytes": 76109103,
        "maxSubtitleRenditionBytes": 32215,
        "audioChannels": 6,
        "videoRange": "SDR",
        "videoCodec": "h.264",
        "audioType": "5.1",
        "audioCodec": "ec-3",
        "averageBandwidth": 652264,
        "frameRate": 23.97
      },
      {
        "bandwidth": 4731436,
        "resolution": "1280x720",
        "videoBytes": 720088332,
        "maxAudioRenditionBytes": 37742146,
        "maxSubtitleRenditionBytes": 32215,
        "audioChannels": 2,
        "videoRange": "SDR",
        "videoCodec": "h.264",
        "audioType": "STEREO",
        "audioCodec": "aac",
        "averageBandwidth": 2550520,
        "frameRate": 23.97
      },
      {
        "bandwidth": 4860113,
        "resolution": "1280x720",
        "videoBytes": 720088332,
        "maxAudioRenditionBytes": 76109103,
        "maxSubtitleRenditionBytes": 32215,
        "audioChannels": 6,
        "videoRange": "SDR",
        "videoCodec": "h.264",
        "audioType": "5.1",
        "audioCodec": "ec-3",
        "averageBandwidth": 2679648,
        "frameRate": 23.97
      },
      {
        "bandwidth": 1600768,
        "resolution": "640x360",
        "videoBytes": 233596439,
        "maxAudioRenditionBytes": 76109103,
        "maxSubtitleRenditionBytes": 32215,
        "audioChannels": 6,
        "videoRange": "SDR",
        "videoCodec": "h.264",
        "audioType": "5.1",
        "audioCodec": "ec-3",
        "averageBandwidth": 1042316,
        "frameRate": 23.97
      },
      {
        "bandwidth": 741399,
        "resolution": "640x360",
        "videoBytes": 117700933,
        "maxAudioRenditionBytes": 18723654,
        "maxSubtitleRenditionBytes": 32215,
        "audioChannels": 2,
        "videoRange": "SDR",
        "videoCodec": "h.264",
        "audioType": "STEREO",
        "audioCodec": "aac",
        "averageBandwidth": 459127,
        "frameRate": 23.97
      },
      {
        "bandwidth": 4056080,
        "resolution": "1280x720",
        "videoBytes": 607273598,
        "maxAudioRenditionBytes": 76109103,
        "maxSubtitleRenditionBytes": 32215,
        "audioChannels": 6,
        "videoRange": "SDR",
        "videoCodec": "h.264",
        "audioType": "5.1",
        "audioCodec": "ec-3",
        "averageBandwidth": 2299960,
        "frameRate": 23.97
      },
      {
        "bandwidth": 7136833,
        "resolution": "1280x720",
        "videoBytes": 916197396,
        "maxAudioRenditionBytes": 76109103,
        "maxSubtitleRenditionBytes": 32215,
        "audioChannels": 6,
        "videoRange": "SDR",
        "videoCodec": "h.264",
        "audioType": "5.1",
        "audioCodec": "ec-3",
        "averageBandwidth": 3339667,
        "frameRate": 23.97
      },
      {
        "bandwidth": 3189313,
        "resolution": "854x480",
        "videoBytes": 524391198,
        "maxAudioRenditionBytes": 76109103,
        "maxSubtitleRenditionBytes": 32215,
        "audioChannels": 6,
        "videoRange": "SDR",
        "videoCodec": "h.264",
        "audioType": "5.1",
        "audioCodec": "ec-3",
        "averageBandwidth": 2021009,
        "frameRate": 23.97
      },
      {
        "bandwidth": 3060636,
        "resolution": "854x480",
        "videoBytes": 524391198,
        "maxAudioRenditionBytes": 37742146,
        "maxSubtitleRenditionBytes": 32215,
        "audioChannels": 2,
        "videoRange": "SDR",
        "videoCodec": "h.264",
        "audioType": "STEREO",
        "audioCodec": "aac",
        "averageBandwidth": 1891881,
        "frameRate": 23.97
      },
      {
        "bandwidth": 1408493,
        "resolution": "640x360",
        "videoBytes": 233596439,
        "maxAudioRenditionBytes": 18723654,
        "maxSubtitleRenditionBytes": 32215,
        "audioChannels": 2,
        "videoRange": "SDR",
        "videoCodec": "h.264",
        "audioType": "STEREO",
        "audioCodec": "aac",
        "averageBandwidth": 849179,
        "frameRate": 23.97
      },
      {
        "bandwidth": 7008156,
        "resolution": "1280x720",
        "videoBytes": 916197396,
        "maxAudioRenditionBytes": 37742146,
        "maxSubtitleRenditionBytes": 32215,
        "audioChannels": 2,
        "videoRange": "SDR",
        "videoCodec": "h.264",
        "audioType": "STEREO",
        "audioCodec": "aac",
        "averageBandwidth": 3210539,
        "frameRate": 23.97
      },
      {
        "bandwidth": 2143633,
        "resolution": "854x480",
        "videoBytes": 349373298,
        "maxAudioRenditionBytes": 37742146,
        "maxSubtitleRenditionBytes": 32215,
        "audioChannels": 2,
        "videoRange": "SDR",
        "videoCodec": "h.264",
        "audioType": "STEREO",
        "audioCodec": "aac",
        "averageBandwidth": 1302849,
        "frameRate": 23.97
      },
      {
        "bandwidth": 3927403,
        "resolution": "1280x720",
        "videoBytes": 607273598,
        "maxAudioRenditionBytes": 37742146,
        "maxSubtitleRenditionBytes": 32215,
        "audioChannels": 2,
        "videoRange": "SDR",
        "videoCodec": "h.264",
        "audioType": "STEREO",
        "audioCodec": "aac",
        "averageBandwidth": 2170832,
        "frameRate": 23.97
      },
      {
        "bandwidth": 2272310,
        "resolution": "854x480",
        "videoBytes": 349373298,
        "maxAudioRenditionBytes": 76109103,
        "maxSubtitleRenditionBytes": 32215,
        "audioChannels": 6,
        "videoRange": "SDR",
        "videoCodec": "h.264",
        "audioType": "5.1",
        "audioCodec": "ec-3",
        "averageBandwidth": 1431977,
        "frameRate": 23.97
      }
    ]
}
```

**Comment by LucianAndries** [comment]
@kentnek So it's official, we need to get our hands on a newer version of the app. If anyone can crack the .emsix package to extract everything.....
There's a tool Microsoft uses, but it's on a special version of Windows. And even then, the file needs decrypted first.

Disney took all this trouble for what? They thought not putting it on Windows, their movies will be safe. But it's the other way around, actually! They are dum! smh

**Comment by kentnek** [comment]
@LucianAndries you can check out the rants [here](https://news.ycombinator.com/item?id=21307308). The main reason is Hollywood doesn't understand tech :joy:

By the way I'm thinking of sniffing traffic from the Android app to see what API it uses. Perhaps it might help writing our own client for FHD/4K resolution hahaha

**Comment by kentnek** [comment]
@LucianAndries I just tried to download the newest version of the `emsix` package, extracted it using [this tool](https://github.com/dalion619/UnpEax), then modified the manifest's target to Windows instead of Xbox. After repackaging and signing it with my own cert, it could install but fail to run :( I guess one doesn't simply sideload an Xbox app on Windows.

![image](https://user-images.githubusercontent.com/7024160/119115329-a51e1580-ba59-11eb-81dc-e710881219e0.png)

EDIT:
Found the error in Event Viewer:
```
Unable to start a DCOM Server: Disney.37853FC22B2CE_1.16.4.70_x64__8x64rcfmpem5g!App as Unavailable/Unavailable. The error:
"2147942593"
Happened while starting this command:
"C:\Program Files\WindowsApps\Disney.37853FC22B2CE_1.16.4.70_x64__8x64rcfmpem5g\DisneyPlus.exe" -ServerName:App.AppXmb6th27g63pfmk4x2bqm0wvb4ms78863.mca
```

`2147942593` stands for [`ERROR_BAD_EXE_FORMAT`](https://stackoverflow.com/a/16329329/4159941), which probably means the EXE for Xbox can't be run on Windows?

**Comment by LucianAndries** [comment]
@kentnek Hey! Yeah, they are pretty ******************...
I'm thinking on the android app myself. If we can get the apk file, maybe we can use some of its components to our own? Different os different codes... But you're way smarter than me. lol

Sniff sniff... lol

**Comment by iContinux** [comment]
Any luck with this? Seems wicked

**Comment by LucianAndries** [comment]
> Any luck with this? Seems wicked

Me personally, no. :(

**Comment by dalion619** [comment]
@kentnek Disney(BAMTech) controls the quality by DRM, anything > 720p requires a version of PlayReady that only Xbox seems to support.

@LucianAndries I've seen experiments done using Android emulators but the same issues exist with Widevine's DRM.

@DiamondFiire No, sadly I think Disney and its other brands like Hulu, ESPN etc. Have made it clear they won't be supporting Windows.

**Comment by kentnek** [comment]
@dalion619 this is not the case if you're using a non-Chrome browser, as the legacy Edge browser could reach 1080p. If Disney+ releases a UWP app for Windows like Netflix, it would support Widevine L1 and as a result 1080p too.

By the way, along with Windows 11 announcement, Microsoft did confirm that Disney+ "will be coming to the Microsoft Store on Windows". [source](https://blogs.windows.com/windowsexperience/2021/06/24/building-a-new-open-microsoft-store-on-windows-11/?fbclid=IwAR2IGCOSQFd430WI6lytaANsoBUHRFeaOsbZ6xMZGQ4Q8TVM9vkhUrY7bOA)

**Comment by dalion619** [comment]
@kentnek Chromium based Edge has experimental support for PlayReady and HEVC decoding which gets offloaded to Windows.
You could try that. 

Netflix on Windows also uses PlayReady, that url you shared from Fiddler can be modified to return the different DRM levels needed for each platform, normally:
Microsoft => PlayReady
Apple => FairPlay
Other => Widevine

Hardware or software implemented decryption is also a factor as well other aspects like HDCP.

**Comment by dalion619** [comment]
@LucianAndries app is back in the store.

**Comment by LucianAndries** [comment]
> @LucianAndries app is back in the store.

Yes, it seems it is, and for Windows..... Yet when I try to install it, it says no device compatible, STILL.
I installed the old cracked one. It seems to work if I log in with a VPN from US.
The idiots still don't know how to make a proper Windows app.

But right now I don't have money to restart the subscription...

Thank you for notifying me, though!👍
